### ISSUE TITLE
Implement tests to ensure data integrity

### ISSUE THREAD

**Issue by NickCrews** [MEDSL/2022-elections-official#10]
Per all the recent issues I've been opening, if we implemented actual tests on the data, then this would

- make it way easier to add new states in the future
- do this work again for 2024 elections (which I assume is going to happen)
- self-document for users exactly what assumptions they can make about the data

Some example tests:

- the district column is never NULL (would catch https://github.com/MEDSL/2022-elections-official/issues/7)
- the state column is one of these 51 values AK, AR, etc
- the office column is one of US HOUSE, US SENATE, etc
- the mode column is one of ...
- the votes column is never negative
- the number of candidates is > 100 (would catch https://github.com/MEDSL/2022-elections-official/issues/11#issuecomment-1977319554)
- etc

I would recommend using python, pytest, and [ibis](https://ibis-project.org/), but other popular frameworks would also be reasonable. I can make a PR that sets up this framework if you are interested.

**Comment by sbaltzmit** [comment]
I sincerely appreciate the energy with which you have been documenting areas of improvement in our 2022 precinct data. You have found several issues that need to be solved, am I am very glad that we know about those problems and can continue to address them. We will energetically go about fixing them, and if any of our fixes don't work or create other issues, or if you find other problems, I really hope you will let us know. These issues, though, were not evidence that we have no data quality tests. We long ago developed a large quality assurance engine in Python, which we described years ago in an open access article [here](https://www.nature.com/articles/s41597-022-01745-0). For each field you named, we have a quality assurance script which runs several automated checks on that field. On the specific issues that you raise:
- Having the district column be sometimes null is deliberate. Often there is no district information, or the notion of a district is not applicable to the office.
- The state column is always the name of a state; if you see any misspellings in that column, or non-state names, please do let me know.
- The office column cannot be constrained that way, because there are thousands and thousands of offices every election, and no way to predict what they will be before the election, but we do look at every single office value, and perform extensive string similarity checks to reduce misspellings in office names.
- You're right that we could be more strict about mode values. At the moment, for 2022, we give a lot of leeway to the reporting jurisdictions to state the vote modes in the descriptive manner of their choice. The 2022 data at present are much looser than they will be after I standardize them across states. They should be standardized within states already though.
- We have such a check. Votes are nonnegative everywhere in 2022. Votes are only negative in 2020 in cases addressed in the readme: Michigan's "statistical adjustment" rows, New Mexico's "masked" votes, and Nevada's privacy protection rows.
